// Original dialogue, plus callbacks to authorized fictional characters and film props.
// No borrowed lyrics, recording samples, third-party band logos, or other franchises.
export const SECRETS = [
  {id:'deputy-bucket',chapter:1,x:340,y:594,kind:'bucket',action:'interact',name:'Deputy Bucket',clue:'Somebody left the smallest deputy beside the road.',text:'You deputize a bucket. Its first official act is holding dirt. Outstanding work.',effect:'badge'},
  {id:'cactus-complaint',chapter:1,x:680,y:450,kind:'cactus',action:'slap',name:'A Prickly Complaint',clue:'One cactus has a real attitude. Get on its level.',text:'The cactus files a formal complaint: “Your hand has too many soft parts.”',effect:'petals'},
  {id:'invisible-horse',chapter:1,x:4390,y:320,kind:'hitch',action:'down',name:'Your Horse Is Here',clue:'Rest your legs at the highest hitching post.',text:'You mount an invisible horse. It refuses to move until you pay for invisible oats.',effect:'horse'},
  {id:'barrel-union',chapter:2,x:570,y:455,kind:'barrel',action:'interact',name:'The Barrel Union',clue:'The rooftop barrels would like a word.',text:'LOCAL 006: BARRELS AGAINST BEING SHOT. Their demands include lids, shade, and dental.',effect:'coins'},
  {id:'tiny-jail',chapter:2,x:1860,y:594,kind:'population',action:'interact',name:'A Full-Time Counting Job',clue:'Mud Bug’s population keeps its sign painter busy.',text:'The population clerk quits. His replacement is a chalk eraser. It demands hazard pay.',effect:'paper'},
  {id:'roof-dentist',chapter:2,x:4400,y:320,kind:'sign',action:'slap',name:'Open Wide, Partner',clue:'The rooftop dentist takes walk-ins and flying fists.',text:'DENTIST / BLACKSMITH. Same pliers. Different appointment book.',effect:'tooth'},
  {id:'stank-review',chapter:3,x:370,y:594,kind:'sign',action:'interact',name:'One-Star Hospitality',clue:'Read the reviews before the showdown.',text:'“Lovely town. Air has a texture.” — Anonymous traveler, immediately leaving.',effect:'badge'},
  {id:'boot-soup',chapter:3,x:680,y:450,kind:'pot',action:'slap',name:'Soup of the Day',clue:'Give the suspicious pot a taste of frontier justice.',text:'The chef retrieves a boot. “That’s our vegetarian option. Cow already left it.”',effect:'boot'},
  {id:'stank-hat',chapter:3,x:2020,y:450,kind:'hat',action:'down',name:'A Moment of Silence',clue:'Bow beneath the hat that nobody claims.',text:'A respectful silence for everyone downwind. The hat drifts three feet farther away.',effect:'hat'},
  {id:'piano-license',chapter:4,x:470,y:594,kind:'piano',action:'interact',name:'Licensed to Honk',clue:'That piano has only one working key.',text:'You play one note. The piano hands you a diploma. “Best we’ve heard all week.”',effect:'notes'},
  {id:'pie-insurance',chapter:4,x:680,y:450,kind:'sign',action:'interact',name:'Acts of Pie',clue:'Read the fine print above the saloon floor.',text:'POLICY EXCLUSIONS: bullets, boots, soup, and any pastry traveling over walking speed.',effect:'paper'},
  {id:'poot-tip',chapter:4,x:2060,y:594,kind:'jar',action:'slap',name:'Generous Gratuity',clue:'That tip jar needs a firm suggestion.',text:'You leave a tip: “Maybe stop throwing dinner at people.” Five-star service follows.',effect:'coins'},
  {id:'ghost-lease',chapter:5,x:1380,y:450,kind:'paper',action:'interact',name:'Haunted, Utilities Extra',clue:'Even the ghosts have paperwork up in the rafters.',text:'The ghost’s lease says “no haunting after ten.” It sighs and gets a second job.',effect:'ghost'},
  {id:'chair-sheriff',chapter:5,x:2950,y:315,kind:'chair',action:'down',name:'Acting Sheriff',clue:'The highest chair has been waiting for someone.',text:'While you sit, the chair becomes acting sheriff. Crime drops. Morale is complicated.',effect:'badge'},
  {id:'last-call',chapter:5,x:4760,y:450,kind:'bell',action:'slap',name:'Last Call for Last Call',clue:'The bell above the back room needs convincing.',text:'You ring last call. A smaller bell rings last call for the first bell. Nobody leaves.',effect:'notes'},
  {id:'tank-manual',chapter:6,x:420,y:594,kind:'paper',action:'interact',name:'Some Assembly Required',clue:'The assassin left his instructions lying around.',text:'TANK ASSEMBLY: attach boots, add menace. WARNING: do not install the personality backwards.',effect:'paper'},
  {id:'spare-bullet',chapter:6,x:680,y:450,kind:'jar',action:'down',name:'Retirement Plan',clue:'Bow to a bullet with big plans.',text:'This bullet is saving up to become a doorbell. You wish it a quieter future.',effect:'notes'},
  {id:'chicken-draft',chapter:6,x:2020,y:450,kind:'chicken',action:'interact',name:'The Poultry Draft',clue:'There’s a volunteer on the high ground.',text:'A chicken volunteers for the cavalry. It brings three references. All eggs.',effect:'chickens'},
  {id:'sanchez-school',chapter:7,x:560,y:450,kind:'sign',action:'slap',name:'Higher Education',clue:'Sanchez’s school sign needs a practical exam.',text:'CLASS DISMISSED. The sign awards your palm an honorary doctorate in applied nonsense.',effect:'paper'},
  {id:'rock-concert',chapter:7,x:3000,y:315,kind:'rock',action:'interact',name:'Sold-Out Rock Show',clue:'The woodland’s highest rock is taking requests.',text:'The rock performs its entire album: forty minutes of sitting there. The crowd goes sedimentary.',effect:'notes'},
  {id:'canyon-echo',chapter:7,x:4860,y:450,kind:'hitch',action:'down',name:'Customer Support Echo',clue:'Take a knee at the lonely woodland post.',text:'Your echo replies: “Your holler is very important to us.” You are caller number seventeen.',effect:'ghost'},
  {id:'chips-accountant',chapter:8,x:360,y:594,kind:'hack',action:'interact',name:'Hack’s Lunch Break',clue:'A silent gunman waits at the start of the final street.',text:'Hack Benjamin points at a pocket watch, then a lunch sack. Even lurking henchmen get a break. You leave him to his sandwich.',effect:'paper'},
  {id:'emergency-mustache',chapter:8,x:680,y:450,kind:'crate',action:'slap',name:'In Case of Identity',clue:'Break the small emergency crate before the last duel.',text:'Inside: a spare gray beard. The receipt is signed “Definitely Not Grizzly.” You file that under deeply suspicious.',effect:'mustache'},
  {id:'tumbleweed-council',chapter:8,x:2060,y:594,kind:'rock',action:'down',name:'The Tumbleweed Council',clue:'Bow to the last street’s least threatening resident.',text:'The tumbleweeds vote unanimously to make you honorary marshal. Their meeting immediately rolls out of town.',effect:'tumbleweeds'}
];
export const secretById=id=>SECRETS.find(s=>s.id===id);
